### ISSUE TITLE
Troubles with 2FA email-code.

### ISSUE THREAD

**Issue by Appolinary111** [greenaddress/GreenAddressWebFiles#100]
Hello. It takes a very long time (>10min.) while my two-factor auth code goes to my email. At the moment when it comes, it's already invalid for the wallet form. What's the troubles?

**Comment by jgriffiths** [comment]
Hi,

We send outgoing emails immediately. Its possible that your email provider only checks for emails/routes them to your inbox every 10 minutes or so, or that their spam checking is slowing things down. Try adding the greenaddress email address to your contact list if possible as this should skip spam detection, otherwise contact your email provider to ask them why deliery is being delayed and how to resolve it (if they tell you when they scan for emails for example, you can wait to request a code 1-2 minutes before that time so it is received in time).

Closing this issue as its not a webfiles bug: please use info@greenaddress.it for support going forward.
